# Generated by Django 4.0.1 on 2022-01-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_variation_delete_variacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacao_categoria', models.CharField(choices=[('color', 'color'), ('size', 'size')], max_length=100)),
                ('variacao_valor', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
