# Generated by Django 4.0.1 on 2022-01-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_rename_variacao_categoria_variacao_variation_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacao',
            old_name='variation_category',
            new_name='variacao_categoria',
        ),
        migrations.RenameField(
            model_name='variacao',
            old_name='variation_value',
            new_name='variacao_valor',
        ),
    ]
