# Generated by Django 4.0.1 on 2022-01-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nome', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, max_length=255)),
                ('cat_imagem', models.ImageField(blank=True, upload_to='fotos/categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
