# Generated by Django 4.0.1 on 2022-01-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_variacao_delete_variation'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='variacoes',
            field=models.ManyToManyField(blank=True, to='loja.Variacao'),
        ),
    ]
