# Generated by Django 4.0.1 on 2022-01-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_carrinhoitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhoitem',
            name='carrinho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrinho.carrinho'),
        ),
    ]
