# Generated by Django 4.0.1 on 2022-01-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_alter_carrinhoitem_carrinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinhoitem',
            old_name='variacoes',
            new_name='variations',
        ),
    ]
